version: "3"
services:
  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: postgres
    pull_policy: build
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend/my-frontend
    pull_policy: build
    ports:
      - "3000:3000"
